### ISSUE TITLE
Epic: Rebuild Kibana logging for edx-platform

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#49]
Saltstack instead of Ansible 1.5

- [ ] #55 write states for elastic search #55 
- [ ] #56 write states for fluentd (replacement for logstash)
- [ ] #57 write states for a log shipper (maybe just syslog)
- [ ] deploy

**Comment by blarghmatey** [comment]
To begin with just continue to use syslog forwarding for log collection. In next steps install log shippers on hosts to forward more logs and do some preprocessing.
