### ISSUE TITLE
Immutable infrastructure epic

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#68]
This is for tracking the tasks necessary to rearchitect our deployment and management of virtual infrastructure. Rather than our current approach of maintaining long-running instances and patching/upgrading them in place we are going to be rebuilding the images and deploying copies of them. This will increase deployment speed as well as preventing a lot of deploy-time issues by letting us verify the final state of a deployed instance before it is actually put into production.
- [x] infrastructure testing (https://github.com/mitodl/salt-ops/issues/8)
- [x] test data management (i.e. having a copy of production db for testing) (https://github.com/mitodl/salt-ops/issues/15)
- [x] run edx-app ansible with salt (https://github.com/mitodl/salt-ops/issues/13)
  - [x] write salt states for mongo cluster & build AMIs (5)
  - [x] build salt states for rabbitmq cluster & build AMIs (5)
  - [x] storage 
- [x] create images with salt (https://github.com/mitodl/salt-ops/issues/9)
- [x] deploying images (spin up, put in place, rotate out old ones) (https://github.com/mitodl/salt-ops/issues/10)
- [x] discovery: how best to customize edX configuration? (https://github.com/mitodl/salt-ops/issues/14)
- [x] service discovery (story exists)
- [x] Determine order of migration for upgrades (https://github.com/mitodl/salt-ops/issues/16)

**Comment by Ferdi** [comment]
Can you pls describe a bit more about what this epic is about ?

**Comment by blarghmatey** [comment]
@Ferdi This is for tracking the tasks necessary to rearchitect our deployment and management of virtual infrastructure. Rather than our current approach of maintaining long-running instances and patching/upgrading them in place we are going to be rebuilding the images and deploying copies of them. This will increase deployment speed as well as preventing a lot of deploy-time issues by letting us verify the final state of a deployed instance before it is actually put into production.

**Comment by Ferdi** [comment]
@blarghmatey ok, I update the ticket description.
